### ISSUE TITLE
Thermostat Object stops responding when humidity above 31 percent. 

### ISSUE THREAD

**Issue by nathantsmith** [PJCzx/homebridge-thermostat#15]
I found that when the humidity reaches higher than 31 percent the thermostat device in the home kit app shows up as unresponsive.  Once I lower it back down  it begins to work again.  Looks like everything outside the the plugin is working properly.

**Comment by paulkoene** [comment]
Mine is 45 percent at the moment and not causing any problems. I've set the target to 47 which doesn't give any problems either. For as far as I can see the plugin doesn't do anything that would explain different behaviour on higher values. What does the homebridge log say about it?

**Comment by nathantsmith** [comment]
I got trigger happy, I was increment temperature as well as humidity and was providing Fahrenheit representation.  Humidity looks to be okay.
