### ISSUE TITLE
Can I use this with a Stelpro STZW402+ thermostat?

### ISSUE THREAD

**Issue by benleroux** [PJCzx/homebridge-thermostat#19]
I have a Stelpro STZW402+ thermostat and was wondering if I can use this pluggin?

From the documentation of the device (http://www.stelpro.com/sites/default/files/fr-CA/guide_utilisateur/INS_STZW402_1215_EN_0.pdf)

Z-Wave Association
The Z-Wave Association Command Class is supported by the thermostat.
The thermostat supports the lifeline as Group1 and only one Node Id is supported in this group (the
Z-Wave controller).
The following reports are sent via the Lifeline :
- Basic Report
- Device Reset Locally Notification
- Thermostat Mode Report
- Thermostat Setpoint Report
- Sensor Multilevel Report
- Thermostat Operating State Report

Z-Wave Basic command class
The Z-Wave Basic command class is supported by the thermostat in the following way:
To trigger the Eco mode on the thermostat: Send it a Basic SET (0x00) command (Energy Saving Mode)
To trigger the Comfort mode on the thermostat: Send it a Basic SET (0xFF) command (Comfort Mode)

**Comment by PJCzx** [comment]
Sorry, my pluggin is dedicated to very custom implementation. You may search a way to send a-wave instructions behind an API. It will then work as a charm ^^

Best
