### ISSUE TITLE
No Humidity

### ISSUE THREAD

**Issue by mark-wade** [PJCzx/homebridge-thermostat#2]
My thermostat does not have a humidity sensor. Is there something I can return for the humidity value  to make it ignore it?

**Comment by PJCzx** [comment]
Humidity is more when managing both heating and cooling. If you don't have cooling system, as a quick fix, you can return an hard coded value (maybe even -1).

As a more long term solution, the HAP documentation lists the mandatory and optional functions to implement. You can have a look at it and comment these lines :)

Is this answering your question?

**Comment by mark-wade** [comment]
That's what I figured. I was hoping you'd know of a way I could just hide those options, but no worries. Thanks - it's working really well :D

**Comment by DirtyDevWork** [comment]
You should be able to just comment out the current and target relative humidity from the Thermostat service (and the implementation in the prototype) as they are both optional to home kit in thermostats :)
