### ISSUE TITLE
README differs from code

### ISSUE THREAD

**Issue by paullj1** [PJCzx/homebridge-thermostat#21]
README States:
* GET `/targetHeatingCoolingState/{INT_VALUE_0_TO_3}`

But `index.js` appears to accept:
```
action = "/off";
action = "/comfort"; // Looks like heat
action = "/auto";
action = "/no-frost"; // Looks like cool
```

Which is correct?

**Comment by paullj1** [comment]
So, just tcpdumped it and it looks like the plugin is sending just like the code says:
`apiroute + action`

Which excludes the `/targetHeatingCoolingState/` as well.

**Comment by PJCzx** [comment]
Yes correct, but I'm looking forward to remove it so deprecated. Kept for compatibility.

**Comment by paullj1** [comment]
Wait, so it only supports one... not both.

**Comment by PJCzx** [comment]
It currently support both, but I'm planning to only stick to the Apple requirement (1,2,3,...) and not to off, comfort, ...

Pierre-Julien Cazaux,

**Comment by PJCzx** [comment]
Btw, I agree what you did with the `targetHeatingCoolingState` but I added a review on your last commit. Thank for your contribution :)
