### ISSUE TITLE
Just Temperature

### ISSUE THREAD

**Issue by prldoyle** [PJCzx/homebridge-thermostat#23]
Hi, I have this working with my home thermostat and it is great, but my thermostat only has temperature control, so is it possible to have the Home App just control temp and not humidity and mode?

**Comment by PJCzx** [comment]
No sorry, it's part of the minimum requirement (modes)

**Comment by phenotypic** [comment]
Neither of the humidity fields are required, they are optional. I have addressed this issue in my [pull request](https://github.com/PJCzx/homebridge-thermostat/pull/35), allowing you to completely disable the humidity fields.
