### ISSUE TITLE
Is it possible to have a maxtemp above 38°C?

### ISSUE THREAD

**Issue by iCarl** [PJCzx/homebridge-thermostat#24]
Id like to use your plugin, but i'd like to know if it's possible to overide the 38°C?

**Comment by PJCzx** [comment]
I’m not sure what you are talking about.

Pierre-Julien Cazaux,

**Comment by iCarl** [comment]
There seems to be a limit to the targetTemperature at 38°C in Homebridge, can I use this plugin in order to set higher values than that?

**Comment by PJCzx** [comment]
Did you used the maxTemp provided in my plugin options ? Can you confirm it is working bellow 38°C and reach kinda thresholds? Maybe the range between maxTemp and minTemp shall be smaller ? Please let me know.

Pierre-Julien Cazaux,

**Comment by iCarl** [comment]
Will try!
