### ISSUE TITLE
Support for Heatmiser

### ISSUE THREAD

**Issue by SupraJames** [PJCzx/homebridge-thermostat#25]
Not really an issue, but I've put together https://github.com/SupraJames/homebridge-heatmiser in the hope that someone finds it useful. It's a server based on your fake.js which implements the API for heatmiser thermostats, using command line calls to https://github.com/thoukydides/heatmiser-wifi.

**Comment by PJCzx** [comment]
Hello,

Thank you for your email. Would you update the readme with your additional info and ask for a Merge Request ?

Thx
