### ISSUE TITLE
php processing

### ISSUE THREAD

**Issue by VanGog86** [PJCzx/homebridge-thermostat#27]
Good afternoon!
I really liked your plugin, I apologize for my English.
I can not understand in any way, I plan to use php to process the values received from the plugin, but for the GET request in the address bar there should be a "?" and in your example I see / targetTemperature / {FLOAT_VALUE} tell me how to get this value in my PHP script?

**Comment by PJCzx** [comment]
You can use the expected value directly in your URL construction a make a request on it without parameters.

**Comment by VanGog86** [comment]
Thanks, I was able to pass the parameters!
Can I specify the temperature range for the thermostat and for the current temperature in the room? The fact is that the current temperature in the room can be from -40 to +40 and the temperature of the thermostat differs from +10 to +30

**Comment by PJCzx** [comment]
Welcome.
You have to keep in mind that you have the Temperature (fact, from thermometer) and the TargetTemperature (objective to be set with the API).
There is a couple of settings to define the max and min value for your thermostat in terms of expectations in the room. These are the same settings than to define if you want °C or °F.
As far as I remember, the min/max value have a possible setting in the conf.json.

Hope I helped,
Best
