### ISSUE TITLE
homebridge doesnt get the data

### ISSUE THREAD

**Issue by lettoka** [PJCzx/homebridge-thermostat#28]
Hi, thank u for uploading. I have a nodejs server running on raspberry pi and i want the homekit to send targetTemperature request and get the data from it.I have added app.get route('/status'... ,but homebridge says it doesnt get any data. I have copied the JSON body what i should return on /status from your readme ,but it shows this error. Any  idea what im doing wrong?

Thanks, 
Levi

**Comment by PJCzx** [comment]
Is the route fully explicit ? (Including http(s)://... ?)

**Comment by lettoka** [comment]
I found the problem. My API was sending 201 in response for getting status but I found an if condition in index.js that needs status code 200, so i changed it, and it works. Is there any chance to display Floats in IOS home app or it can only show ints? I changed MinStep to 0.1 in your index.js but nothing have changed in home app, it only shows integer.

**Comment by PJCzx** [comment]
Ok, 

Maybe you should look at Characteristics (update) but maybe it’s overkill and not worth it.

If you find something, don’t hesitate to make a PullRequest.

In the meantime, can you please close the issue ?

Thx
