### ISSUE TITLE
Remove setCurrentHeatingCoolingState characteristic

### ISSUE THREAD

**Issue by DirtyDevWork** [PJCzx/homebridge-thermostat#3]
CurrentHeatingCoolingState is a read only Characteristic in HAP-NodeJS, so the setCurrentHeatingCoolingState entry doesn't really serve a purpose

**Comment by PJCzx** [comment]
Indeed ! I just pushed the change. It was the opportunity to remove this lame log of mine "TO BE REMOVED BECAUSE USELESS setCurrentHeatingCoolingState:".

Thx for the feedback.

**Comment by PJCzx** [comment]
As it's just code cleaning, I don't publish on npm (no functional change). I'll do it for bigger changes ^^ Any suggestion ?

**Comment by DirtyDevWork** [comment]
Nothing jumps to mind right away, but if it does (or I come up with something useful in my fork), then I'll pop open a issue and prefix it with "Enhancement:" for ya! :)
