### ISSUE TITLE
Does thermostat support adjust the fan state?

### ISSUE THREAD

**Issue by mistak1992** [PJCzx/homebridge-thermostat#30]
Thank U. I'm new here, and i have setup my AC to HomeKit this awesome plugin successfully. And i want to know more about the thermostat in homeKit, but it's seem to be ambiguous in develop document. so...i am here to ask for help...

**Comment by PJCzx** [comment]
Basically, you declare an Accessory that provide a set of Services in order ton manage Characteristics.

I implemented the very basic behavior for a thermostat with target and mesured temperatures and humidity.

Please note the target most interesting value is « AUTO » were the mesured will always be a fact « MORE/LESS/IDDLE ».

Knowing this, and by following the exemples, you might be able to add the fan state and fan target state to the existing code.

To help you, please find bellow the documentation to the Thermostat documentation page : https://developer.apple.com/documentation/homekit/hmservicetypethermostat

Please proceed to a Pull Request once you managed successfully th integration :)

Best,
PJCzx
