### ISSUE TITLE
Error: connect EALREADY

### ISSUE THREAD

**Issue by Homeelec** [PJCzx/homebridge-thermostat#31]
Hello,
First of all thank you for the plugin.
After installing the plugin I have an error in the log files
See log
Can you help me?

{ Error: connect EALREADY 192.168.1.244:3310 - Local (192.168.1.241:48890)
Aug 30 13:00:15 sdomotica homebridge[3810]:     at Object._errnoException (util.js:1003:13)
Aug 30 13:00:15 sdomotica homebridge[3810]:     at _exceptionWithHostPort (util.js:1024:20)
Aug 30 13:00:15 sdomotica homebridge[3810]:     at internalConnect (net.js:967:16)
Aug 30 13:00:15 sdomotica homebridge[3810]:     at net.js:1067:9
Aug 30 13:00:15 sdomotica homebridge[3810]:     at process._tickCallback (internal/process/next_tick.js:150:11)
Aug 30 13:00:15 sdomotica homebridge[3810]:     at Function.Module.runMain (module.js:703:11)
Aug 30 13:00:15 sdomotica homebridge[3810]:     at startup (bootstrap_node.js:193:16)
Aug 30 13:00:15 sdomotica homebridge[3810]:     at bootstrap_node.js:617:3
Aug 30 13:00:15 sdomotica homebridge[3810]:   errno: 'EALREADY',
Aug 30 13:00:15 sdomotica homebridge[3810]:   code: 'EALREADY',
Aug 30 13:00:15 sdomotica homebridge[3810]:   syscall: 'connect',
Aug 30 13:00:15 sdomotica homebridge[3810]:   address: '192.168.1.244',
Aug 30 13:00:15 sdomotica homebridge[3810]:   port: 3310 }
Aug 30 13:00:15 sdomotica homebridge[3810]: { Error: connect EALREADY 192.168.1.244:3310 - Local (192.168.1.241:48890)
Aug 30 13:00:15 sdomotica homebridge[3810]:     at Object._errnoException (util.js:1003:13)
Aug 30 13:00:15 sdomotica homebridge[3810]:     at _exceptionWithHostPort (util.js:1024:20)
Aug 30 13:00:15 sdomotica homebridge[3810]:     at internalConnect (net.js:967:16)
Aug 30 13:00:15 sdomotica homebridge[3810]:     at net.js:1067:9
Aug 30 13:00:15 sdomotica homebridge[3810]:     at process._tickCallback (internal/process/next_tick.js:150:11)
Aug 30 13:00:15 sdomotica homebridge[3810]:     at Function.Module.runMain (module.js:703:11)
Aug 30 13:00:15 sdomotica homebridge[3810]:     at startup (bootstrap_node.js:193:16)
Aug 30 13:00:15 sdomotica homebridge[3810]:     at bootstrap_node.js:617:3
Aug 30 13:00:15 sdomotica homebridge[3810]:   errno: 'EALREADY',
Aug 30 13:00:15 sdomotica homebridge[3810]:   code: 'EALREADY',
Aug 30 13:00:15 sdomotica homebridge[3810]:   syscall: 'connect',
Aug 30 13:00:15 sdomotica homebridge[3810]:   address: '192.168.1.244',
Aug 30 13:00:15 sdomotica homebridge[3810]:   port: 3310 }

**Comment by PJCzx** [comment]
Hello, did you used a complete URL with http(s):// ?

**Comment by Homeelec** [comment]
Thank you
It s ok

Home Electricité
Fuziol Sacha
06 20 89 03 65

**Comment by PJCzx** [comment]
;)

PS : I suggest you to remove your personal signature from Github ^^

**Comment by Homeelec** [comment]
Merci
