### ISSUE TITLE
Can't get it working with Infinitude

### ISSUE THREAD

**Issue by Tangston311** [PJCzx/homebridge-thermostat#33]
I'm trying to get this hooked up to an Infinitude implementation to gain control of my Bryant thermostat.  I've got Infinitude up and running (which gives me local web-based control of the thermostat), but I'm pretty new to this and I'm not sure how to set up the API call to get it working.

I tried to look at the Heatmiser API example but I'm having trouble translating that to my specific implementation.  Do you have any other examples I could look at?  Or any experience with getting it hooked up with Infinitude?

Sorry for the newbie question, but any help would be greatly appreciated!
Guthrie

**Comment by PJCzx** [comment]
Hello,

Don’t the API Expectations section of the ReadMe or the working demo of the fake.js API helps you?

Thx in advance for providing specific questions that I may answer ;)

Best,
PJCzx

**Comment by Tangston311** [comment]
It does, and sorry for the basic questions - I've just never done this before so I'm stumbling my way through it!  I suppose my two questions are:

1. I'm not sure what values within the fake.js file I need to update to get it functioning.  Which values should I update to get the fake.js file to become a real.js and actually pull the correct data from my system? 

2. Once I've updated the fake.js file, what do I do then?  I'm running homebridge off an old MacBook Pro, so do I need to store the file in a specific location on my Mac and have the API URL use the IP of my Mac and the directory where the .js file is stored?

Thank you so much!

**Comment by PJCzx** [comment]
Hello, 

Well, it depends on what are you using. I don’t know Infinitude not Bryant systems but I assume you can mesure température somewhere and heat somewhere else :)

Basically, you have the target values that you would like to reach and the current values that are facts. Eg

targetHeatingCoolingState = 3 (AUTO) (see [HAP|https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js] mean you want the heating to manage by itself. So if you use the app to click Auto, you will receive this in the fake.js and you will need to manage the case.

Remember this plugin is made to build something and cannot work as a standalone solution. I suggest you start both side by side and play with your Home iOS app while looking at the logs.

My setup was 2 raspberries pies, one with homeBridge and one with the heating system mechanism and temperature measurement.

I used a similar implementation of the fake.js on the hardware rPi to store temperature and give heater orders.

If you try it, you will see each time you open Home app on iOS device Homebrige will ask your Fake status, and each time you will change some settings in the app, it will call target temperature or target heating.

Hope this is useful for you, please remember the IP must be fully writen, like http://127.0.0.1, not just the numbers.

Best,

**Comment by PJCzx** [comment]
No news after >10 days. Good news ? I Close :) Best

**Comment by Tangston311** [comment]
Sorry I didn't see your reply! Thank you for all of the info - I haven't had a chance to work on it over the past week but this is helpful and gives me something to go on; I'll see how far I can get.  Really appreciate your help.
