### ISSUE TITLE
No Response error

### ISSUE THREAD

**Issue by phenotypic** [PJCzx/homebridge-thermostat#34]
Hi there,

I've had a lot of fun with this project, however, I am having a problem both with this plugin: every now and then, when I open the Home app, all devices appear as `No Response`. I believe other people have had similar problems with this plugin  [#17](https://github.com/PJCzx/homebridge-thermostat/issues/17)). All it takes is closing and re-opening the app for the messages to reset. 

This problem is becoming increasingly annoying however, and this is why I am seeking help. Note that this problem only occurs when using this plugin; furthermore, when this plugin is isolated on my test "Home" with no other plugins, the issue does not occur. Thus, it seems the problem only occurs when in the same "Home" as multiple other accessories, and, at that, only every now and then (I'd say 1 in 5 times or if I haven't opened the Home app in a few minutes). 

After running Homebridge in debug mode (`DEBUG=* homebridge -D`), something strange happens. Whenever I get the `No Response` error in the Home app, the following 5 lines always appear at the end of the debug log (where `192.168.1.36` is the local IP of my iPhone):

```
  EventedHTTPServer [::ffff:192.168.1.36] HTTP Response is finished +3ms
  EventedHTTPServer [::ffff:192.168.1.36] Writing pending HTTP event data +1ms
  EventedHTTPServer [::ffff:192.168.1.36] Client connection closed +113ms
  EventedHTTPServer [::ffff:192.168.1.36] HTTP connection was closed +2ms
  EventedHTTPServer [::ffff:192.168.1.36] HTTP server was closed +1ms
```

These lines never appear in this order anywhere else as long as there is no `No Response` error (the first 2 lines appear frequently by themselves elsewhere, but the last 2/3 only appear during this error). Any ideas on what might be causing the plugin to make this happen?

Thank you in advance for your help,

Kind regards, Tom

**Comment by PJCzx** [comment]
@Tommrodrigues I this problem persist after your pull request ? I updated npm as + homebridge-thermostat@0.0.46 version.

Best,

**Comment by phenotypic** [comment]
No, the issue has been around since I first became aware of the plugin. However, I feel the issue may not be due to the plugin as the issue is noted elsewhere due to network problems (like [here](https://github.com/nfarina/homebridge/issues/1361)).

Thanks anyway
