### ISSUE TITLE
Pull request not merged

### ISSUE THREAD

**Issue by phenotypic** [PJCzx/homebridge-thermostat#37]
Hi, thanks for authorising my pull request. However, it looks like you overwrote it:

<img width="1033" alt="screenshot 2019-02-19 at 21 15 48" src="https://user-images.githubusercontent.com/33377034/53044552-a7b0ef80-348b-11e9-93ea-98314da67a9e.png">

Note the `Merge branch 'master' of https://github.com/PJCzx/homebridge-thermostat`

You can see this simply if you compare [my README](https://github.com/Tommrodrigues/homebridge-thermostat) with yours. But this also applies to the `index.js`. Shall I make a new pull request?

Best, Tom

**Comment by PJCzx** [comment]
@Tommrodrigues : my bad, it must be better now ;) Can you confirm please ? nom is now v0.0.47 :p

**Comment by phenotypic** [comment]
@PJCzx Great, thanks. All looks good now via `npm` :)
