### ISSUE TITLE
One click activation of thermostat devices

### ISSUE THREAD

**Issue by macjl** [PJCzx/homebridge-thermostat#46]
Hello,

I think it would be great if we can turne on/off thermostat devices with just one click in Home App. It has been done in the homebridge-daikin-local plug-in, and working very well for me :
(cbrandlehner/homebridge-daikin-local#15)

The way it has been done in this plugin was adding this characteristic : 
```
    this.heaterCoolerService
      .getCharacteristic(Characteristic.Active)
      .on('get', this.getActive.bind(this))
      .on('set', this.setActive.bind(this)); 
```

With the 'setActive' action, the thermostat is powered up / powered down with just a click on the icon in Home app.

Do you think it's possible to implement it?

Regards

**Comment by phenotypic** [comment]
Hi there,

Unfortunately, what you have listed above will not work with this plugin. The plugin you have referenced exposes a `Fan` and `HeaterCooler` service. This plugin exposes the `Thermostat` service, which does not support the `Active` characteristic.

Please refer to the [HAP specification](https://developer.apple.com/homekit/specification/) for more information on services and their supported characteristics.

Best, Tom

**Comment by macjl** [comment]
Hello,

I've understood from an other project that HeaterCooler is the new version of accessory type for this devices :
https://github.com/RavenSystem/esp-homekit-devices/issues/609#issuecomment-555216382

Do you think the work would be high to migrate to this new service?

**Comment by PJCzx** [comment]
Hello @macjl and thank you for your feedback.

HeaterCooler is not a replacement, it's another device that behave differently. Basically, a Thermostat is "the boss" and decides when the system should run or not... 

If you want to set the system on, ask for a global higher temperature or review the way you get the room temperature ;)

Best,
PJCzx
