### ISSUE TITLE
Accessory with http base auth

### ISSUE THREAD

**Issue by mariusz2108** [PJCzx/homebridge-thermostat#5]
Is there any way to pass username and password to url when connecting to accessory?
I found username and password params  in httpReques but I don't know how to pass them.
Does httpRequest function is used anywhere?

**Comment by PJCzx** [comment]
Are you refering to as user/pswd for the http request? if yes, this is not supported but this may be an improvment either via an extra work of mine or a pull request of yours :)

**Comment by mariusz2108** [comment]
Yes it is user/pswd for the http request.
I will add it to config file and make pull request :)

**Comment by PJCzx** [comment]
Great thanks !
