### ISSUE TITLE
pollInterval does not work

### ISSUE THREAD

**Issue by lp4so** [PJCzx/homebridge-thermostat#52]
Hi,
I'm pleased with your plugin, but the pollInterval doesn't seem to work.

Thanks.

**Comment by PJCzx** [comment]
Hello @lp4so could you please be a little bit more explicit (expected behavior and observed ?) 

Thx :)

**Comment by lp4so** [comment]
Bonjour,

Vu ton nom, j’imagine que tu es Français alors ça sera plus simple comme ça 😉

Eh bien, j’ai configuré un pollInterval de 30s, et rien ne se passe après 30s, pas de polling pour détecter les nouvelles valeurs.
J’ai maté vite fait le code, et le terme pollInterval n’apparait pas non plus.

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : Pierre-Julien Cazaux<mailto:notifications@github.com>
Envoyé le :mercredi 6 mai 2020 09:38
À : PJCzx/homebridge-thermostat<mailto:homebridge-thermostat@noreply.github.com>
Cc : lp4so<mailto:l.p@live.fr>; Mention<mailto:mention@noreply.github.com>
Objet :Re: [PJCzx/homebridge-thermostat] pollInterval does not work (#52)


Hello @lp4so<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flp4so&data=02%7C01%7C%7C5d7fe42471cf4920941c08d7f1906b42%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637243474878261150&sdata=idaPaj3NwnEPWc9D2cz3SXaYWZFI6iwnFDl9JX7wW2s%3D&reserved=0> could you please be a little bit more explicit (expected behavior and observed ?)

Thx :)

**Comment by PJCzx** [comment]
Hello,

en effet je ne voit pas de référence à ce paramètre y compris dans la doc d’Apple. As-tu quelque chose sous la main ? Au besoin tu peux faire un pull request mais l’idéal est de rester le plus générique possible. Comme je n’ai pas fait des test auto, plus on met du spécifique plus on augment le risque de régressions pour tout le monde.

Tiens moi au courant :)

—-

Indeed I don't see any reference to this parameter even in the Apple doc.  Do you have something to share?  You can make a pull request if you need it but the best is to stay as generic as possible.  As I didn't implemented automatic-tests, the more specific code you put the more you increase the risk of regressions for everyone.
Keep me in touch :)

**Comment by lp4so** [comment]
J’ai utilisé le plugin homebridge-http-thermostat et là le polling fonctionne... Tu peux y jeter un coup d’œil pour voir comment s’est réalisé, parce que je n’ai pas exactement bien capté 😁

Le 24 mai 2020 à 13:26, Pierre-Julien Cazaux <notifications@github.com> a écrit :

﻿

Hello,

en effet je ne voit pas de référence à ce paramètre y compris dans la doc d’Apple. As-tu quelque chose sous la main ? Au besoin tu peux faire un pull request mais l’idéal est de rester le plus générique possible. Comme je n’ai pas fait des test auto, plus on met du spécifique plus on augment le risque de régressions pour tout le monde.

Tiens moi au courant :)

—-

Indeed I don't see any reference to this parameter even in the Apple doc. Do you have something to share? You can make a pull request if you need it but the best is to stay as generic as possible. As I didn't implemented automatic-tests, the more specific code you put the more you increase the risk of regressions for everyone.
Keep me in touch :)

**Comment by lp4so** [comment]
Homebridge-http-thermostat ou Homebridge-web-thermostat, je sais plus 😉

Le 24 mai 2020 à 13:26, Pierre-Julien Cazaux <notifications@github.com> a écrit :

﻿

Hello,

en effet je ne voit pas de référence à ce paramètre y compris dans la doc d’Apple. As-tu quelque chose sous la main ? Au besoin tu peux faire un pull request mais l’idéal est de rester le plus générique possible. Comme je n’ai pas fait des test auto, plus on met du spécifique plus on augment le risque de régressions pour tout le monde.

Tiens moi au courant :)

—-

Indeed I don't see any reference to this parameter even in the Apple doc. Do you have something to share? You can make a pull request if you need it but the best is to stay as generic as possible. As I didn't implemented automatic-tests, the more specific code you put the more you increase the risk of regressions for everyone.
Keep me in touch :)
