### ISSUE TITLE
Generic thermostat in Home Assistant

### ISSUE THREAD

**Issue by jharmn** [PJCzx/homebridge-thermostat#7]
When using a Home Assistant server, coupled with homebridge-homeassistant, this thermostat accessory doesn't work. To provide a compatibility layer, I created a proxy between your thermostat accessory and the API in Home Assistant. 

https://github.com/jharmn/homebridge-homeassistant-thermostat
https://hub.docker.com/r/jharmn/docker-homebridge-homeassistant-thermostat/builds/

Feel free to close the issue and ignore, I just thought you might want to share the option for Home Assistant users.

**Comment by PJCzx** [comment]
Hello @jharmn, as I'm not a Home Assistant user, feel free to push your work as pull request as you did a few days ago. I will integrate it as soon as possible.

Thank you for your contribution :)
